# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6921edca9420692d8b3f3172a8c7fef8b43c1788439b32cbf509b6874afcd39cd84c458d7f88bd55e6bcd839eb4b7116ebb6d3b6abf4313c219e8c554c73663

test:
  secret_key_base: 500ad2f3a2e0b06e1d7dafad3f87d69a6089b20dc4b4dd8c3a9d1a20c1e7121650172fb19ac0d1119b91adfb79dd64f3ce2b5601c0bffbdcb11e4302890ba020

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
